version: '3'
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"
  flask:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=api/app.py
      - pixabaykey=${pixabaykey}
      - bingkey=${bingkey}
