FROM python:3.7
WORKDIR /app

COPY api/requirements.txt api/*.py api/.flaskenv ./
RUN pip install -r ./requirements.txt
ENV FLASK_ENV production

EXPOSE 5000
# WORKDIR /app/api
CMD ["gunicorn", "-b", ":5000", "api:app"]