# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - TortoiseVsTurtleWebApp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_2649c80fe9d9481aabb9e45a416b74ea }}
        password: ${{ secrets.AzureAppService_ContainerPassword_bfdbc293187b4df1b0f6f235a89a5d59 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_2649c80fe9d9481aabb9e45a416b74ea }}/tortoise_vs_turtle:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'TortoiseVsTurtleWebApp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5831d5f42e314c7a9885badbc1bd3b3c }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_2649c80fe9d9481aabb9e45a416b74ea }}/ganievart/tortoise_vs_turtle:${{ github.sha }}'