name: Trigger auto deployment for tortoise-vs-turtle-container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/tortoise-vs-turtle-container-app-AutoDeployTrigger-d547e585-5d6b-42a8-9432-319ce0e5aaa2.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: tortoisevsturtlecontainer.azurecr.io
          username: ${{ secrets.TORTOISEVSTURTLECONTAINERAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.TORTOISEVSTURTLECONTAINERAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: tortoisevsturtlecontainer.azurecr.io/tortoise-vs-turtle-container-app:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.TORTOISEVSTURTLECONTAINERAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n tortoise-vs-turtle-container-app -g artur-resource-group --server tortoisevsturtlecontainer.azurecr.io --username  ${{ secrets.TORTOISEVSTURTLECONTAINERAPP_REGISTRY_USERNAME }} --password ${{ secrets.TORTOISEVSTURTLECONTAINERAPP_REGISTRY_PASSWORD }}
            az containerapp update -n tortoise-vs-turtle-container-app -g artur-resource-group --image tortoisevsturtlecontainer.azurecr.io/tortoise-vs-turtle-container-app:${{ github.sha }}
